### ISSUE TITLE
AttributeError: 'GRU' object has no attribute 'get_initial_states'

### ISSUE THREAD

**Issue by akhilgentoo** [saurabhmathur96/Neural-Chatbot#5]
Creating model with configuration: ModelConfig(sequence_length=8, vocabulary_size=2048, hidden_size=256, weights_path='models/seq2seq_weights.h5')
Traceback (most recent call last):
  File "src/model/sample.py", line 16, in <module>
    model = seq2seq_attention(sequence_length, vocabulary_size, hidden_size)
  File "/home/infinitylabs/Documents/Neural-Chatbot-master/src/model/models.py", line 60, in seq2seq_attention
    x = AttentionDecoder(hidden_size, activation=activation, return_sequences=True, bidirectional=bidirectional_decoder, use_gru=use_gru)(x, attention)
  File "/home/infinitylabs/Documents/Neural-Chatbot-master/src/model/sequence_blocks.py", line 172, in _decoder
    go_backwards=False), attention, single_attention_param=True)(x)
  File "build/bdist.linux-x86_64/egg/keras/engine/topology.py", line 587, in __call__
  File "/home/infinitylabs/Documents/Neural-Chatbot-master/src/model/sequence_blocks.py", line 102, in call
    initial_states = self.layer.get_initial_states(x)
AttributeError: 'GRU' object has no attribute 'get_initial_states'

**Comment by saurabhmathur96** [comment]
It seems you are using the incorrect version of Keras. Follow the instructions under Getting Started in README.md.

**Comment by akhilgentoo** [comment]
Thank you,let me see to it
Will keep you posted

**Comment by akhilgentoo** [comment]
so,what version do you prefer?,i have seen this version issue before being raised?

**Comment by saurabhmathur96** [comment]
see requirements.txt

**Comment by akhilgentoo** [comment]
should i install everything inside the requirements.txt??



https://paste.debian.net/980770/

**Comment by gokulgsachu** [comment]
python train.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from batch_utils import BatchIterator
ImportError: No module named batch_utils

Error occur while train data

**Comment by akhilgentoo** [comment]
same error i have

**Comment by akhilgentoo** [comment]
Thank you ,above issue has be solved.Problem was the version of keras and excecution path was wrong...
